=== project-ncl/sbomer/core/src/main/resources/schemas/config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://jboss.org/sbomer/config.json",
  "title": "SBOMer user configuration file",
  "description": "User-provided configuration file to instruct SBOM generation",
  "type": "object",
  "$defs": {
    "processor-default": {
      "$id": "/schemas/processors/default",
      "type": "object",
      "properties": {
        "type": {
          "const": "default"
        }
      }
    },
    "processor-redhat-product": {
      "$id": "/schemas/processors/redhat-product",
      "type": "object",
      "properties": {
        "type": {
          "const": "redhat-product"
        },
        "errata": {
          "description": "Product information from Errata Tool",
          "type": "object",
          "properties": {
            "productName": {
              "description": "Errata Tool product name",
              "type": "string"
            },
            "productVersion": {
              "description": "Errata Tool product version",
              "type": "string"
            },
            "productVariant": {
              "description": "Errata Tool product variant",
              "type": "string"
            }
          },
          "required": ["productName", "productVersion", "productVariant"],
          "additionalProperties": false
        }
      },
      "required": ["errata"],
      "additionalProperties": false
    }
  },
  "properties": {
    "apiVersion": {
      "description": "Version of the configuration file",
      "enum": ["sbomer.jboss.org/v1alpha1"]
    },
    "buildId": {
      "description": "PNC build identifier",
      "type": "string"
    },
    "products": {
      "description": "List of product configurations",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "generator": {
            "description": "Generator configuration",
            "type": "object",
            "properties": {
              "buildId": {
                "description": "The PNC build identifier",
                "type": "string"
              },
              "type": {
                "description": "Type of generator",
                "enum": [
                  "maven-cyclonedx",
                  "maven-domino",
                  "gradle-cyclonedx",
                  "nodejs-cyclonedx",
                  "maven-cyclonedx-operation"
                ]
              },
              "args": {
                "description": "Optional custom arguments that are passed to the generator",
                "type": "string"
              },
              "version": {
                "description": "Version of the generator",
                "type": "string"
              }
            },
            "required": ["type"],
            "additionalProperties": false
          },
          "processors": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "maxItems": 2,
            "prefixItems": [
              {
                "$ref": "#/$defs/processor-default"
              },
              {
                "$ref": "#/$defs/processor-redhat-product"
              }
            ],
            "items": false
          }
        },
        "additionalProperties": false
      }
    },
    "environment": {
      "description": "Environment used at build time",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": ["products"],
  "additionalProperties": false
}

=== project-ncl/sbomer/e2e/src/test/resources/requests/A3YCIKLQTVYAA.json
{
  "apiVersion": "sbomer.jboss.org/v1alpha1",
  "buildId": "A3YCIKLQTVYAA",
  "environment": {
    "gradle": "5.6.2",
    "java": "8",
    "maven": "3.6.0"
  },
  "products": [
    {
      "processors": [
        {
          "type": "redhat-product",
          "errata": {
            "productName": "RHTESTPRODUCT",
            "productVersion": "RHEL-8-RHTESTPRODUCT-1.1",
            "productVariant": "8Base-RHTESTPRODUCT-1.1"
          }
        }
      ],
      "generator": {
        "type": "gradle-cyclonedx",
        "version": "1.7.3"
      }
    }
  ]
}
