=== project-ncl/sbomer/core/src/main/resources/schemas/deliverable_analysis_config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://jboss.org/sbomer/deliverables-analysis-operation-config.json",
  "title": "SBOMer user configuration file",
  "description": "User-provided configuration file to trigger a PNC deliverable analysis operation",
  "type": "object",
  "properties": {
    "apiVersion": {
      "description": "Version of the configuration file",
      "enum": ["sbomer.jboss.org/v1alpha1"]
    },
    "type": {
      "description": "Configuration type",
      "enum": ["analysis"]
    },
    "milestoneId": {
      "description": "PNC milestone identifier",
      "type": "string"
    },
    "errata": {
      "description": "Product information from Errata Tool",
      "type": "object",
      "properties": {
        "productName": {
          "description": "Errata Tool product name",
          "type": "string"
        },
        "productVersion": {
          "description": "Errata Tool product version",
          "type": "string"
        },
        "productVariant": {
          "description": "Errata Tool product variant",
          "type": "string"
        }
      },
      "required": ["productName", "productVersion", "productVariant"],
      "additionalProperties": false
    },
    "deliverableUrls": {
      "description": "List of deliverables urls",
      "type": "array",
      "items": {
        "type": "string",
        "description": "The deliverable url",
        "additionalProperties": false
      }
    }
  }, 
  "required": [
    "milestoneId", "deliverableUrls", "type"
  ],
  "additionalProperties": false
}

=== project-ncl/sbomer/core/src/test/resources/configs/analysis.json
{
    "apiVersion": "sbomer.jboss.org/v1alpha1",
    "type": "analysis",
    "milestoneId": "3101",
    "errata": {
        "productName": "RHBOAC",
        "productVersion": "RHBOAC CSB 4.8 Text-only",
        "productVariant": "6Server-RHBOAC-CSB-4.8"
    },
    "deliverableUrls": ["https://host.com/rcm-guest/staging/rhaf/camel-4.8.0.ER1/rhaf-camel-4.8.0.ER1-maven-repository.zip ", "https://host.com/rcm-guest/staging/rhaf/camel-spring-boot-4.8.0.CS1/rhaf-camel-spring-boot-4.8.0.CS1-maven-repository.zip"]
}
